development: 
    clientId: VWCLZCDP3IJI3QA33LA0VCIQGASAUAQDI0B0H14AAE2OI0VC
    clientSecret: Y0BWGQ3TJGVLZY0QZIPKGOQVDDNPJJEFGR05FE204NHITODW
    redirectUri: http://localhost:3000/authenticate/

production: 
    clientId:00WU15WUYS1QBU0LW0ZKXRUYUS0PJKRCLLI5SMECYELN25BX
    clientSecret:2CYYKMTA045GUROSNCIOJOKR4SUIQWOYILVLNZGCXR1AKKND
    redirectUri:http://sporkmap.com/authenticate/

test:
    clientId:VWCLZCDP3IJI3QA33LA0VCIQGASAUAQDI0B0H14AAE2OI0VC
    clientSecret:Y0BWGQ3TJGVLZY0QZIPKGOQVDDNPJJEFGR05FE204NHITODW
    redirectUri:http://localhost:3000/authenticate/

